// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestCase.Api.Integration.Test.Tests.User.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetCustomerByIdQueryFeature : object, Xunit.IClassFixture<GetCustomerByIdQueryFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetCustomerByIdQuery.feature"
#line hidden
        
        public GetCustomerByIdQueryFeature(GetCustomerByIdQueryFeature.FixtureData fixtureData, TestCase_Api_Integration_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests/User/Features", "GetCustomerByIdQuery", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Retrieve Customer Information by Id with GET Request")]
        [Xunit.TraitAttribute("FeatureTitle", "GetCustomerByIdQuery")]
        [Xunit.TraitAttribute("Description", "Retrieve Customer Information by Id with GET Request")]
        public virtual void RetrieveCustomerInformationByIdWithGETRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve Customer Information by Id with GET Request", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "FirstName",
                            "LastName",
                            "DateOfBirth",
                            "PhoneNumber",
                            "Email",
                            "BankAccountNumber",
                            "CreatedDate"});
                table12.AddRow(new string[] {
                            "11111111-1111-1111-1111-111111111111",
                            "Ali",
                            "YILDIRIM",
                            "DATE_ONLY-12d",
                            "5554443322",
                            "ali@ali.com",
                            "1234567890",
                            "2024-04-01"});
                table12.AddRow(new string[] {
                            "22222222-2222-2222-2222-222222222222",
                            "Fuat",
                            "YILDIRIM",
                            "DATE_ONLY-11d",
                            "6664443322",
                            "fuat@fuat.com",
                            "2234567890",
                            "2024-04-01"});
                table12.AddRow(new string[] {
                            "33333333-3333-3333-3333-333333333333",
                            "Ali Fuat",
                            "YILDIRIM",
                            "DATE_ONLY-10d",
                            "6664443322",
                            "yildirim@yildirim.com",
                            "3234567890",
                            "2024-04-01"});
#line 4
        testRunner.Given("Customers are", ((string)(null)), table12, "Given ");
#line hidden
#line 9
        testRunner.When("GET \"/customer/{11111111-1111-1111-1111-111111111111}\" is called", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
        testRunner.Then("Http status code should be 200 and Message should be \"\" and error code should be " +
                        "\"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "DateOfBirth",
                            "PhoneNumber",
                            "Email",
                            "BankAccountNumber"});
                table13.AddRow(new string[] {
                            "Ali",
                            "YILDIRIM",
                            "DATE_ONLY-12d",
                            "5554443322",
                            "ali@ali.com",
                            "1234567890"});
#line 11
        testRunner.Then("Get Customer should be", ((string)(null)), table13, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetCustomerByIdQueryFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetCustomerByIdQueryFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
